# Site settings
title: 개인위키
url: "http://devbj.com/wiki/"
baseurl: "/wiki"
description: >
    

# My information
email: bjnhur@gmail.com
author: Bongjun
profile: 
twitter_username: 
github_username: 
disqus_shortname: 

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: 
  shortname: 

google_analytics:
  ua: 

google_adsense:
  client: 

blame: "https://github.com/bjnhur/wiki/blame/master/_wiki"
edit: "https://github.com/bjnhur/wiki/edit/master/_wiki"
issue: "https://github.com/bjnhur/wiki/issues/new"

timezone: "Asia/Seoul"
